### ISSUE TITLE
module not found after pip install

### ISSUE THREAD

**Issue by tabroughton** [ApproxEng/approxeng.input#1]
Please can you help me?  My daughter and I are trying to get ready for piwars but we're very stuck with any kind of remote control and we are hoping to use your python package :) 

We are getting module not found from when importing the input package though and we really can't understand why this is happening - here's an output of what we have on our system and hopefully you can point out anything obvious.  

```
pi@raspberrypi:~ $ pip show approxeng.input
---
Name: approxeng.input
Version: 0.5
Location: /usr/local/lib/python2.7/dist-packages
Requires: evdev
pi@raspberrypi:~ $ sudo python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print '\n'.join(sys.path)

/usr/local/lib/python2.7/dist-packages/grovepi-0.0.0-py2.7.egg
/usr/lib/python2.7
/usr/lib/python2.7/plat-arm-linux-gnueabihf
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/root/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
>>> import approxeng.input
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named approxeng.input
```

**Comment by tabroughton** [comment]
found the issue, with RPi3, running Jessie when pip install or setuptools the `__init__.py` is missing in the parent approxeng dir... not sure why as I can see it's in the src - maybe it's because it's a 0 byte file perhaps it gets removed/skipped?

`$touch <path to packages dir>/approxeng/__init__.py `

has fixed for me

**Comment by tomoinn** [comment]
I think this is just broken in the upload to pip, I should really fix that but as I pretty much entirely develop from my own github checkouts it may not have happened!

On a related note, you may or may not be aware that virtualenv exists - it means you can do a lot of this stuff without using sudo as you work in a local version of python with full access as a regular user. If you do that, and checkout this repository, you can do 'python setup.py develop', which will link the files in the checked out repo to your installation. Of course, depending on what you're doing you may need to be root *anyway*, but I prefer to avoid touching the system Python installation if possible!

**Comment by tabroughton** [comment]
yes, maybe something not quite right with the way installs as root - I've tried both pip and cloning your git repo and running `setup.py install` both install to same dir (slightly differently) but both have their `__init__.py` missing - maybe something with my configuration...

I like the idea of virtualenv, will look into that more as we get further into development (and after piwars) - we are finding the learning curve difficult and becoming familiar with just the basics to get things working is taking us ages, each thing is frustratingly complex (to us).  We're getting there though and hope there's another next year so we can continue.

Thanks so much for this package, I think it'll be amazing for us (and others).

**Comment by tabroughton** [comment]
hi Tom, just thought I'd mention that I've just uses pip install - couldn't import approxeng.input again as missing __init_.py in parent folder (approxeng) - I've created it in the there to get it workign. 
suspect this isn't me though it could be... (I just fried my sd and had to reinstall everything, not good this close to piwars)

**Comment by tomoinn** [comment]
There were issues with missing files and (more recently) with empty __init__.py files in conjunction with multiple approxeng.* packages, these should all be fixed in the versions here but I've not done an upload to PyPi yet, waiting on v2 for a full release

**Comment by tomoinn** [comment]
This is (I believe) all fixed now, partly because I actually had to add contents to the __init__.py files to get them to work when I started having multiple approxeng.something packages (i.e. combining approxeng.input and approxeng.holochassis)
