### ISSUE TITLE
Feature to add: Unknown button number finder

### ISSUE THREAD

**Issue by recantha** [ApproxEng/approxeng.input#10]
At the moment, show_controls is used to show what buttons and controls are being used, depending on the controller configuration activated. When you're trying to configure or create a new controller type and you're pressing the buttons, notification that an Unknown Button or control is shown by the underlying code. However, the curses commands in the main loop in show_controls is continually clearing the screen, which means the error messages either don't appear or they appear and straight away get cleared. Feature request is to either allow this script to pick up the unknown buttons/controls and display the numerical code to access them in the configuration. Alternatively, a new script could be written specifically to allow the identification of these buttons/commands.

**Comment by tomoinn** [comment]
I think this is covered by evtest, but I'll add a section describing it to the docs.
