### ISSUE TITLE
PS4 Wireless Controller with Pi 3 and Stretch

### ISSUE THREAD

**Issue by alancairns** [ApproxEng/approxeng.input#11]
I'm unable to get the PS4 controller working using a Raspberry Pi 3 with the current updated Raspian Stretch and wondered if there is an issue with Raspian Stretch. Below is a summary of my observations.

Using the Raspberry Pi 3 with a clean install of Raspian Version "9 Stretch" I installed approving.input as follows:
   sudo apt-get install python-dev python-pip gcc
   sudo apt install python3-gpiozero
   sudo apt install python3-dev gcc
   pip install approxeng.input
   pip3 install approxeng.input

I then created a python script buttonsHeld.py  by copying the python script from the Simple Usage

I connected the PiHut Compatible Wireless Gamepad / Controller and ran the buttonsHeld.py script and this worked.

I shutdown the Pi, disconnected the PiHut controller, booted the PI and paired the PS4 Wireless controller (had to connect the paired controller manually). When I ran buttonsHeld.py it continually printed "Unable to find any joystick" to the console.

ls -l /dev/input listed js0 as a device which I assume is the PS4 wireless controller

To eliminate the hardware I installed the RetroPie OS on the Raspberry Pi 3 and configured the PS4 controller. I tested the controller using the jstest /dev/input/js0 and this worked.

I would be grateful if you could shed any light on this.

Regards

Alan Cairns

**Comment by tomoinn** [comment]
Hi Alan,

Can you check you're using the latest version of the library? Someone else had a very similar problem with the PS4 controller and it turned out to be because it had a different USB product ID to mine, I added that into the latest release which was pushed to PyPi a couple of days ago.

Other than that, can you run the 'list devices' script and paste the output here, that'll tell me everything I need to know about whether your controller is paired, and what IDs it's using.

**Comment by tomoinn** [comment]
(the list devices script is just a single command - https://github.com/ApproxEng/approxeng.input/blob/master/scripts/list_devices.py)

**Comment by alancairns** [comment]
Hi Tom

Thank you so much from your prompt reply.

I’ve downloaded the latest library, both python and python3, and received the message “successfully installed approxeng.input-2.0.2 evaded-0.6.4” for both. Now when I run buttonsHeld.py it prints the following:

found a joystick and connected
Unknown axis code 44, value 8003
Unknown axis code 45, value 8011
Unknown axis code 43, value 1548
and continues like this.

I then ran controllerProperties.py (copied from the Showing Controller Properties example on the Approximate Engineering site)

last presses:
axes: lt=0.00 lx=0.00 ly=0.00 rt=0.00 rx=0.00 ry=0.00
hold times:
controller class: DualShock4

{ 'axes': ['lt', 'lx', 'ly', 'rt', 'rx', 'ry'],
  'buttons': [ 'circle',
               'cross',
               'ddown',
               'dleft',
               'dright',
               'dup',
               'home',
               'l1',
               'l2',
               'ls',
               'ps4_pad',
               'r1',
               'r2',
               'rs',
               'select',
               'square',
               'start',
               'triangle’]}

but an error “Unknown axis code 44, value 8003 intermittently flashes up at the bottom of the screen print.

I also ran list_devices.py but received the following errors:

pi@rasp3pi01st:~/gitRepos/python/gameController $ python3 list_devices.py
Traceback (most recent call last):
  File "list_devices.py", line 3, in <module>
    print_devices()
  File "/home/pi/.local/lib/python3.5/site-packages/approxeng/input/controllers.py", line 125, in print_devices
    pp.pprint(device_verbose_info(device))
  File "/home/pi/.local/lib/python3.5/site-packages/approxeng/input/controllers.py", line 132, in device_verbose_info
    axis_code, axis_info in device.capabilities().get(3)}
  File "/home/pi/.local/lib/python3.5/site-packages/approxeng/input/controllers.py", line 132, in <dictcomp>
    axis_code, axis_info in device.capabilities().get(3)}
KeyError: 41
pi@rasp3pi01st:~/gitRepos/python/gameController $ python list_devices.py
Traceback (most recent call last):
  File "list_devices.py", line 3, in <module>
    print_devices()
  File "/home/pi/.local/lib/python2.7/site-packages/approxeng/input/controllers.py", line 125, in print_devices
    pp.pprint(device_verbose_info(device))
  File "/home/pi/.local/lib/python2.7/site-packages/approxeng/input/controllers.py", line 132, in device_verbose_info
    axis_code, axis_info in device.capabilities().get(3)}
  File "/home/pi/.local/lib/python2.7/site-packages/approxeng/input/controllers.py", line 132, in <dictcomp>
    axis_code, axis_info in device.capabilities().get(3)}
KeyError: 41L

Regards

Alan

**Comment by tomoinn** [comment]
Okay, this is all rather strange. Those axis codes don't exist in linux/input-event-codes.h, which is where they should be found. They're certainly not the axis codes I'd expect from this controller, and their absence from ecodes is also why you're getting an error from the list_devices script. So basically you've got a controller which is sending events that nothing should expect.

Is it working, in the sense of showing any axis changes when you move the sticks? My first thought was that these were accelerometer axes, which I don't see here, but maybe not.

**Comment by alancairns** [comment]
Here are result segments of various python scripts which were copied from your site:

buttonsHeld.py

Unknown axis code 40, value 55
Unknown axis code 43, value 1827
Unknown axis code 40, value 96
Unknown axis code 44, value 7940
Unknown axis code 45, value 1607
Unknown axis code 40, value 128
Unknown axis code 43, value 1814
Unknown axis code 44, value 7884
Unknown axis code 43, value 1806
Unknown axis code 44, value 7849
Unknown axis code 45, value 1594
Unknown axis code 43, value 1771
Unknown axis code 44, value 7839
Unknown axis code 45, value 1580
Unknown axis code 43, value 1709
Unknown axis code 44, value 7826
Unknown axis code 45, value 1548
Unknown axis code 43, value 1512
Unknown axis code 44, value 7773
Unknown axis code 45, value 1535
Unknown axis code 43, value 1469
Unknown axis code 43, value 1435
Cross held for 0.16273021698 seconds
Unknown axis code 43, value 1422
Unknown axis code 43, value 1790
Unknown axis code 45, value 1347
Unknown axis code 43, value 1831
Unknown axis code 44, value 7826
Unknown axis code 45, value 1356
Unknown axis code 43, value 1840
Unknown axis code 45, value 1486
Unknown axis code 43, value 1890
Unknown axis code 44, value 7786
Unknown axis code 45, value 1519
Unknown axis code 43, value 1931
Unknown axis code 44, value 7797
Unknown axis code 45, value 1529
Unknown axis code 43, value 1731
Unknown axis code 44, value 7830
Unknown axis code 45, value 1515
Unknown axis code 43, value 1526
Unknown axis code 45, value 1476
Unknown axis code 43, value 1489
Unknown axis code 45, value 1464
Unknown axis code 43, value 1502
Unknown axis code 44, value 7844
Unknown axis code 45, value 1454
Unknown axis code 43, value 1729
Unknown axis code 44, value 7879
Unknown axis code 43, value 1860
Unknown axis code 44, value 7868
Unknown axis code 45, value 1462
Note: the valid lines occur very intermittently



findController.py

Unknown axis code 40, value 55
Unknown axis code 43, value 1827
Unknown axis code 40, value 96
Unknown axis code 44, value 7940
Unknown axis code 45, value 1607
Unknown axis code 40, value 128
Unknown axis code 43, value 1814
Unknown axis code 44, value 7884
Unknown axis code 43, value 1806
Unknown axis code 44, value 7849
Unknown axis code 45, value 1594
Unknown axis code 43, value 1771
Unknown axis code 44, value 7839
Unknown axis code 45, value 1580
Unknown axis code 43, value 1709
Unknown axis code 44, value 7826
Unknown axis code 45, value 1548
Unknown axis code 43, value 1512
Unknown axis code 44, value 7773
Unknown axis code 45, value 1535
Unknown axis code 43, value 1469
Unknown axis code 43, value 1435
Cross held for 0.16273021698 seconds
Unknown axis code 43, value 1422
Unknown axis code 43, value 1790
Unknown axis code 45, value 1347
Unknown axis code 43, value 1831
Unknown axis code 44, value 7826
Unknown axis code 45, value 1356
Unknown axis code 43, value 1840
Unknown axis code 45, value 1486
Unknown axis code 43, value 1890
Unknown axis code 44, value 7786
Unknown axis code 45, value 1519
Unknown axis code 43, value 1931
Unknown axis code 44, value 7797
Unknown axis code 45, value 1529
Unknown axis code 43, value 1731
Unknown axis code 44, value 7830
Unknown axis code 45, value 1515
Unknown axis code 43, value 1526
Unknown axis code 45, value 1476
Unknown axis code 43, value 1489
Unknown axis code 45, value 1464
Unknown axis code 43, value 1502
Unknown axis code 44, value 7844
Unknown axis code 45, value 1454
Unknown axis code 43, value 1729
Unknown axis code 44, value 7879
Unknown axis code 43, value 1860
Unknown axis code 44, value 7868
Unknown axis code 45, value 1462
Note: the valid lines occur very intermittently



controllerProperties.py

last presses:
axes: lt=0.00 lx=0.00 ly=0.00 rt=0.00 rx=0.00 ry=0.00
hold times:
controller class: DualShock4

{ 'axes': ['lt', 'lx', 'ly', 'rt', 'rx', 'ry'],
  'buttons': [ 'circle',
               'cross',
               'ddown',
               'dleft',
               'dright',
               'dup',
               'home',
               'l1',
               'l2',
               'ls',
               'ps4_pad',
               'r1',
               'r2',
               'rs',
               'select',
               'square',
               'start',
               'triangle']}




This script displays the correct values for each of the axes (-1.00 to 1.00) and displays the correct button and hold times. However it also flashes up Unknown axis code…. messages regularly.

The odd thing is that it works on RetroPie using the jstest command.

I would like to thank you for the time you are spending on this.

Alan

**Comment by tomoinn** [comment]
This is kernel related. Apparently in some kernels the DS4 reports motion sensor data on ABS axes that are outside the evdev spec (see https://patchwork.kernel.org/patch/9444429/ for discussion). On my controller and the kernels I've tested (4.4 and 4.11) I'm not seeing these, but the 4.11 kernel screws up the other axis mappings so something's changing!

The most sensible fix is to suppress the warning messages, assuming everything else under 4.9 is working as intended. It'd be nice to actually support the motion sensors, but there seems a degree of debate about how they'll surface in different kernels, I guess I'll take a look and see whether there's a sane way to do it for Raspbian Stretch because that's going to be the most common request. I imagine the DS3 might be doing something similar with that kernel series.

**Comment by tomoinn** [comment]
On 4.8 on my workstation the axis mappings are correct and I'm not seeing any motion events. I suspect, based on the kernel mailing list thread in the last comment, that these will only appear for your particular revision of the DS4 as they're identifying by USB product ID the same as I do in this library.

**Comment by alancairns** [comment]
With my limited knowledge I’m afraid that I can only follow the gist of this, not the detail. Is it possible to suppress the warning messages in the python scripts and if so can you suggest how?

**Comment by tomoinn** [comment]
Upshot is - with your specific controller you're seeing motion events which
I don't get because my controller is a different revision and the linux
support for them doesn't handle this properly! I'm making a change to the
code to use the logging API rather than just printing stuff, so in the next
version those messages will go away.

**Comment by alancairns** [comment]
Thanks

**Comment by tomoinn** [comment]
Updated - do a 'pip install -U approxeng.input' and you should have a
version which isn't quite so shouty

**Comment by alancairns** [comment]
Hi Tom

I’m afraid this didn’t work. Below is a segment of the output I get running buttonHeld.py


pi@rasp3pi01st:~/gitRepos/python/gameController $ python buttonsHeld.py
[D 171016 16:43:51 controllers:59] Attempting to find controller using driver class <class 'approxeng.input.dualshock3.DualShock3'>
[D 171016 16:43:51 controllers:59] Attempting to find controller using driver class <class 'approxeng.input.dualshock4.DualShock4'>
[W 171016 16:43:51 __init__:295] Unknown axis code 45, value 1545
Found a joystick and connected
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8016
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8024
[W 171016 16:43:51 __init__:295] Unknown axis code 43, value 160
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8016
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8008
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 7998
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8011
[W 171016 16:43:51 __init__:295] Unknown axis code 43, value 150
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8020
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8028
[W 171016 16:43:51 __init__:295] Unknown axis code 43, value 160
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8018
[W 171016 16:43:51 __init__:295] Unknown axis code 45, value 1536
[W 171016 16:43:51 __init__:295] Unknown axis code 45, value 1544
[W 171016 16:43:51 __init__:295] Unknown axis code 43, value 150
[W 171016 16:43:51 __init__:295] Unknown axis code 43, value 160
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8007
[W 171016 16:43:51 __init__:295] Unknown axis code 43, value 169
[W 171016 16:43:51 __init__:295] Unknown axis code 45, value 1552
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 7999
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8012
[W 171016 16:43:51 __init__:295] Unknown axis code 45, value 1544
[W 171016 16:43:51 __init__:295] Unknown axis code 43, value 157
[W 171016 16:43:51 __init__:295] Unknown axis code 44, value 8045
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8033
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8023
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 166
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 156
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 146
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8034
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 154
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8043
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8034
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8024
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1552
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1540
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1548
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8013
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 163
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1557
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8005
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 7995
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8005
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 170
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8037
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 157
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 145
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8027
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8015
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8005
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 154
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8015
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8027
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8039
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8047
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 93
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 7874
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1804
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 153
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8033
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1562
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 194
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8066
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1411
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1466
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 158
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8054
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1643
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8044
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1634
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8036
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1618
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1604
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1590
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 148
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8027
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1576
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1566
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1553
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 7995
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8002
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8015
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8023
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8011
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 137
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 7968
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1564
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 148
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8113
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1597
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 156
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8097
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1553
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 145
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 7967
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1540
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 136
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 7980
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 144
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8125
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1571
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8115
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8059
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 7929
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1562
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 7961
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 152
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8008
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 161
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8020
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 152
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 160
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 168
[W 171016 16:43:52 __init__:295] Unknown axis code 44, value 8028
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 159
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1552
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1543
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 150
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1552
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1543
[W 171016 16:43:52 __init__:295] Unknown axis code 43, value 158
[W 171016 16:43:52 __init__:295] Unknown axis code 45, value 1554
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1567
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1577
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1568
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 7983
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1557
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 7968
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1545
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8002
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8012
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1578
[W 171016 16:43:53 __init__:295] Unknown axis code 43, value 149
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8004
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1587
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1578
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1564
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1551
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8015
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8028
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8019
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1542
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1550
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1563
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8011
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1553
[W 171016 16:43:53 __init__:295] Unknown axis code 43, value 162
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8019
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8027
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1544
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1551
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8019
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8009
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1542
[W 171016 16:43:53 __init__:295] Unknown axis code 45, value 1551
Circle held for 1.36237311363 seconds
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8018
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8006
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8015
[W 171016 16:43:53 __init__:295] Unknown axis code 43, value 153
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 8006
[W 171016 16:43:53 __init__:295] Unknown axis code 44, value 7996

**Comment by tomoinn** [comment]
That's working as intended - you need to set the logging level, i.e.

```python
approxeng.input.logger.setLevel(logging.ERROR)
```

**Comment by alancairns** [comment]
Thank you so much!

Alan
