### ISSUE TITLE
Axis merge when identical codes are specified

### ISSUE THREAD

**Issue by tomoinn** [ApproxEng/approxeng.input#16]
The wii controller, because it has optional extensions, has multiple mappings from code -> the same axis. In the definition this doesn't work, the one defined second over-writes the one defined first and so only one of the axes on the controller will send events to that sname. The Controller (or maybe Axes) class should detect this and create a merged axis of some kind that accepts input from either axis and immediately pushes it through to a shared one that is then surfaced by the controller instance, that way events coming in on any of a set of codes would be usable. There's a question as to whether it's raw values or centred and dead/hot zone corrected ones that would be pushed through, presumably the latter as there's no guarantee that the physical devices pushing the event codes will have the same range just because they conceptually map to the same sname.

This basically happens with the wii because it's possible to connect either the nunchuck (with a single joystick) or the classic controller (similar, but different evdev codes) and we really want e.g. both evdev codes for the x-axis on each extension to map to the same surfaced axis in the controller instance, that being the most obvious way for it to work and therefore the correct one as far as users are concerned.

**Comment by insonnecensore** [comment]
why don't you simply change variable names in wiimote.py?
...
                CentredAxis("Nunchuck Y", -100, 100, 17, sname="ry"),
                CentredAxis("Nunchuck X", -100, 100, 16, sname="rx"),
                CentredAxis("Classic lx", -32, 32, 18, sname="lx"),
                CentredAxis("Classic ly", -32, 32, 19, sname="ly"),
                CentredAxis("Classic rx", -32, 32, 20, sname=**"rx"),**
                CentredAxis("Classic ry", -32, 32, 21, sname=**"ly"),**
...
I've choosen "cx" and "cy" instead of "rx" and "ly" and it works. I'll manage variables in my code.

**Comment by tomoinn** [comment]
That will work of course, but in general one of the aims of the library is to make the same code work on multiple controllers. As it's impossible to connect both the nunchuck and the classic controller at the same time it should be possible to map both to the same axis name in which case this problem wouldn't happen (as described in the initial issue). Otherwise you have a configuration which is suddenly missing its rx,ry axes and code that expects them won't work. It's not a huge issue and I don't own one of these controllers so I'm unlikely to fix it any time soon.
