### ISSUE TITLE
Xbox One wireless button mappings incorrect

### ISSUE THREAD

**Issue by DougGore** [ApproxEng/approxeng.input#17]
I noticed on my Xbox One controller some of the wireless mappings appear to be incorrect. I don't know if it's specific my model variant or a general issue.

In particular:
X shows up as:
[W 180114 23:00:45 __init__:797] Unknown button code 306

Y maps to square and not triangle

View and Menu are mapped to l1 and r1 instead of Select and Start
LB maps to triangle

RB shows up as:
[W 180114 23:04:17 __init__:797] Unknown button code 309

The left and right analogue buttons when pushed give:
[W 180114 23:04:45 __init__:797] Unknown button code 312
[W 180114 23:04:50 __init__:797] Unknown button code 313

The controller is a Bluetooth based model with an integrated headphone socket.

**Comment by tomoinn** [comment]
I've seen this before, as have others, it's something to do with the version of the firmware on the controller. I had to change the mappings (to their current values) after connecting my XB1 (bluetooth) controller to my PC to play a few games, that updated the controller in some way and the events it emits under evdev changed at that point. It *might* just go away as a problem if you disconnect and reconnect (as reported in discord) but I don't really understand why that would help. It's a bit of an odd one.

If you have access to a Win10 PC or, presumably, to an XB1 console, could you try letting it update the controller firmware and see if that solves things?

**Comment by DougGore** [comment]
I've checked the firmware version and tried an update (via Windows 10), it appears I'm already running the latest version which is 3.1.1221.0

**Comment by tomoinn** [comment]
This was from Graham Collins (via discord a while ago) and I've seen similar:

gcollins - 29/12/2017
hello
thickie question...
just got a new xbox 1 controller and downloaed your SW;
the x button (aka triangle) is coming up under LB - and the x button itself is doing nothing....
ideas?
RB does nothing
all else is fine
(using your Showing Controller Properties code)
(select and sqaure are also playing up)
scrub that....well, not sure what happended....but removed and re-paired the device
all working again!???!!!
will check again when / if issue next happens!
31 December 2017

I can't say for sure that the behaviour of mine changed when I updated it with my windows box, it could have been what Graham's seen here. If you're the 'doug' on discord you could poke him there?

**Comment by DougGore** [comment]
Confirmed, removing and repairing solved issue "by magic". I can only assume the issue lies somewhere in the device driver.

**Comment by tomoinn** [comment]
Weird. I'll add to the docs that this might happen!

**Comment by DougGore** [comment]
I booted up the robot again today and it seems to have gone back to that weird state. I'll investigate further but I wonder if it's ok when first paired and then mapping changes in the next session.

**Comment by tomoinn** [comment]
That's odd, I've not seen that as a problem - I used this controller for my most recent 'bot and it works on bootup every time. I've added some notes to the docs, hopefully we can get something that consistently works!

**Comment by tsunatr** [comment]
Hello,
I had same problem on Right stick analogs and L2-R2. I solve it with changing on library codes. I opened the xboxone.py at /home/pi/.local/lib/python2.7/site-packages/approxeng/input/xboxone.py , changed keymap at WirelessXboxOneSPad from
```
  CentredAxis("Right Horizontal", 0, 65335, 3, sname='rx'),
  CentredAxis("Right Vertical", 0, 65335, 4, invert=True, sname='ry'),
        TriggerAxis("Left Trigger", 0, 1023,2, sname='lt',button_sname='l2', button_trigger_value=0.1),
         TriggerAxis("Right Trigger", 0, 1023, 5, sname='rt',button_sname='r2', button_trigger_value=0.1),
```
to
```
 CentredAxis("Right Horizontal", 0, 65335, 2, sname='rx'),
    CentredAxis("Right Vertical", 0, 65335, 5, invert=True,sname='ry'),
 TriggerAxis("Left Trigger", 0, 1023, 3, sname='lt' button_sname='l2', button_trigger_value=0.1)    
TriggerAxis("Right Trigger", 0, 1023, 4, sname='rt',button_sname='r2', button_trigger_value=0.1),
```
Result is satisfying for me, right analog works well after this change but triggers are not working so 3-4 is not any button. I don't need triggers on Rpi so i didn't mind it. You can find it with trying numbers or another way which i don't know.

**Comment by tomoinn** [comment]
This is almost certainly a kernel version problem. If this still happens with the latest (4.15 series) kernels I'll worry about it, but if not it's just how it is. There have been substantial changes with bluez and the handling of input devices in recent kernels and they've basically fixed a bunch of inconsistent behaviours that affected my library code.

**Comment by milosblag** [comment]
Hi. I had a similar problem and fixed it by installing [xpadneo](https://github.com/atar-axis/xpadneo) Advanced Linux Driver for Xbox One Wireless Controller. After installing the driver I had to change the mappings to be the same as the WiredXBoxOneSPad in the /home/pi/.local/lib/python3.5/site-packages/approxeng/input/xboxone.py and everything worked (even the lt and rt Triggers). Hope it helps others as a see that this issue is quiet for a while.

**Comment by keithellis74** [comment]
I seem to have the same problem with my Wireless XBox one controller.  bought very recently and firmware upgraded yesterday (30/11/2019) via the XBox.  I have tried the un-pair/re-pair  but this did not change anything for me.

The `start` and `select` buttons and the left and right triggers do not return anything for me.  Some other mappings seem to be off too.

  ```
  (venv) pi@raspberrypi:~/repo/approxeng.input/scripts $ uname -a
  Linux raspberrypi 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux
```
```
(venv) pi@raspberrypi:~/repo/approxeng.input/scripts $ python list_devices.py 
{ 'axes': { 'ABS_BRAKE': {'code': 10, 'flat': 63, 'fuzz': 3, 'max': 1023, 'min': 0, 'res': 0},
            'ABS_GAS': {'code': 9, 'flat': 63, 'fuzz': 3, 'max': 1023, 'min': 0, 'res': 0},
            'ABS_HAT0X': {'code': 16, 'flat': 0, 'fuzz': 0, 'max': 1, 'min': -1, 'res': 0},
            'ABS_HAT0Y': {'code': 17, 'flat': 0, 'fuzz': 0, 'max': 1, 'min': -1, 'res': 0},
            'ABS_RZ': {'code': 5, 'flat': 4095, 'fuzz': 255, 'max': 65535, 'min': 0, 'res': 0},
            'ABS_X': {'code': 0, 'flat': 4095, 'fuzz': 255, 'max': 65535, 'min': 0, 'res': 0},
            'ABS_Y': {'code': 1, 'flat': 4095, 'fuzz': 255, 'max': 65535, 'min': 0, 'res': 0},
            'ABS_Z': {'code': 2, 'flat': 4095, 'fuzz': 255, 'max': 65535, 'min': 0, 'res': 0}},
  'bus': 5,
  'buttons': { 158: 'KEY_BACK',
               304: ['BTN_A', 'BTN_GAMEPAD', 'BTN_SOUTH'],
               305: ['BTN_B', 'BTN_EAST'],
               306: 'BTN_C',
               307: ['BTN_NORTH', 'BTN_X'],
               308: ['BTN_WEST', 'BTN_Y'],
               309: 'BTN_Z',
               310: 'BTN_TL',
               311: 'BTN_TR',
               312: 'BTN_TL2',
               313: 'BTN_TR2',
               314: 'BTN_SELECT',
               315: 'BTN_START',
               316: 'BTN_MODE',
               317: 'BTN_THUMBL',
               318: 'BTN_THUMBR'},
  'fn': '/dev/input/event0',
  'name': 'Xbox Wireless Controller',
  'path': '/dev/input/event0',
  'phys': 'b8:27:eb:1d:e6:ae',
  'product': 765,
  'rel_axes': None,
  'uniq': '98:7a:14:0d:71:dc',
  'unique_name': '98:7a:14:0d:71:dc',
  'vendor': 1118,
  'version': 2307}
```

**Comment by keithellis74** [comment]
Hi Tom,
I've just tried this again on a new Raspberry Pi 4 and still getting the same issues.  Disconnecting and re-pairing does not work for me.  Any ideas how I can get this to work?

**Comment by bradwalbeck** [comment]
Confirmed still and issue; Please advise.
