### ISSUE TITLE
unusual readings

### ISSUE THREAD

**Issue by nezra** [ApproxEng/approxeng.input#28]
Board: Beaglebone blue, running kernel 4.14
Controller: Dualshock 3 Model CECHZC2U
Script: running the updated "show_controls.py" script

when I change the pitch of the controller, LT shows a value affected by the pitch. 

When i move the left stick, 
Lx varies between -.5 and 1
Ly varies berween .5 and -1
it also changes based on the pitch or roll i move the device. it impacts Lx and Ly changing these values until i move with the left stick again.

Pressing L2(lt) increases to 1, then stops at .18 when full pressed

Pitch and roll never change from 0.00.
Battery level never changes from 1.00.

Rx and ry  change as expected. from 1 to -1 on both axes.

All the button presses show as expected.

Any idea why this does this?

**Comment by tomoinn** [comment]
(old issue, kernel versions and similar matter so while this was probably a genuine problem it's unlikely to be valid *now* and will have been replaced by similar but different problems. This is because the kernel and evdev hate the earth)
