### ISSUE TITLE
Controller class formet

### ISSUE THREAD

**Issue by keithellis74** [ApproxEng/approxeng.input#32]
The format for the `controller class` files seems to have changed and the documentation for adding a new class nolonger works.  Can this be updated please.
cheers,
Keith.

**Comment by tomoinn** [comment]
I welcome all pull requests...

**Comment by kneave** [comment]
PR raised :)

**Comment by tomoinn** [comment]
I think that's now up-to-date, although it's largely superceded by the profiling. I guess there may still be some obscure controllers out there with more widgets than that supports though so good to have it correct.
