### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by rirze** [ApproxEng/approxeng.input#34]
As title says:

I'm looking for a project that supports gamepad controllers on any OS. Some of the other packages that are popular in Python are unmaintained as far as I can tell. This one, however, seems to be more recently updated than the others. 

Do you plan on supporting this package for the foreseeable future? I don't want to base my new project on a package that won't be updated properly.

Thanks.

**Comment by tomoinn** [comment]
No guarantees, and this project very specifically supports linux so I don't know whether it would be suitable for your needs. It's quite focused on the use of controllers with robotics, although it's possible to use it for other things. If that's what you need then it'll most likely be supported.

**Comment by rirze** [comment]
No worries- fwiw I'm looking for a gamepad library to integrate with a custom robotics library. While I personally work on Linux, I'd imagine users on Windows as well. 

All I want to clarify is that critical patches be applied if they should be found and a fix is provided in an PR. 

Thanks for your timely response

**Comment by tomoinn** [comment]
I'm happy to merge well constructed PRs subject to review (in general the requirement is 'the PR also updates the docs'!). This code is very much linux only though, and there's no chance it'll work on Windows of any flavour, sitting as it does on top of evdev. If you need cross-platform support it's not going to work for you, but it should be applicable if you can stick with linux.

**Comment by rirze** [comment]
Gotcha-- sorry about the OS comments, I was confusing aspects of another library with this one. 

Anyways, that's good to know and I'll keep that in mind as I decide soon. I don't have anything else to add, so I'll close the issue as well.

Thanks for taking the time to answer my questions.
