### ISSUE TITLE
WiiMote pointer

### ISSUE THREAD

**Issue by SirKillalot** [ApproxEng/approxeng.input#36]
Hi, it is possible to retrieve coordinates from WiiMote?
Thanks

**Comment by tomoinn** [comment]
If the wiimote presents itself as a device or devices within /dev/input then yes, although I don't own one so I can't test it. I can help you to write the necessary extension code though if you're able to get it connected in the first place.

**Comment by SirKillalot** [comment]
Thanks a lot. 
It is possible to use this library with a USB device like USB joypad or wheel?

**Comment by tomoinn** [comment]
You really need to read the docs... Short answer, again, is that if the device creates nodes within /dev/input (which most will) then it's possible to write a class that'll let you use that device.

**Comment by SirKillalot** [comment]
thank you so much
