### ISSUE TITLE
Trying to install on Pi 4

### ISSUE THREAD

**Issue by binaryhellstorm** [ApproxEng/approxeng.input#38]
I get this error when trying to install

Collecting approxeng.input
  Using cached https://files.pythonhosted.org/packages/1c/27/418500122ddff3e29355c5f248b20690555102c59037961968583262ae55/approxeng.input-2.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bbupn4v0/approxeng.input/setup.py", line 2, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bbupn4v0/approxeng.input/
You are using pip version 8.1.1, however version 20.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by tomoinn** [comment]
Hi - as the error is telling you (the last line of your output) you're running a very old version of pip that doesn't understand the 'find_namespace_packages' directive. You need to upgrade pip using the command at the bottom of the output you've included.

Do that, and ensure you're using Python 3 rather than 2, and you should be fine.

**Comment by binaryhellstorm** [comment]
Ah Ok I accidentally updated pip vs pip3. Pip3 is updated now and I get this:
ubuntu@ubiquityrobot:~$ pip3 install approxeng.input
Defaulting to user installation because normal site-packages is not writeable
Collecting approxeng.input
  Using cached approxeng.input-2.4.2.tar.gz (24 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-49abr5nx/approxeng-input/setup.py'"'"'; __file__='"'"'/tmp/pip-install-49abr5nx/approxeng-input/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-h_z9iqap
         cwd: /tmp/pip-install-49abr5nx/approxeng-input/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-49abr5nx/approxeng-input/setup.py", line 2, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by tomoinn** [comment]
You need to update setuptools as well by the looks, it's finding an old version which doesn't support namespace packages
