### ISSUE TITLE
Controller not detected on Ubuntu 20.04 LTS aarch64

### ISSUE THREAD

**Issue by ghost** [ApproxEng/approxeng.input#48]
Hi there,

It seems that controllers are not detected on the aarch Ubuntu 20.04 (Kernel: Linux 5.4.0-1028-raspi aarch64) version for Raspberry Pi. ([Downloaded here](https://ubuntu.com/download/raspberry-pi))
I tried running `approxeng_input_list_devices` while a controller is connected, but no output was returned there. With the same controller I do get correct output on RaspiOS (tested on Raspberry Pi 3) and on Ubuntu 20.04 LTS x86_64 (Kernel: Linux 5.8.0-44-generic x86_64).
Running `ls /dev/input/` shows `js0` which should be the controller because it disappears after I plug it out. So I guess the device itself is recognized by the system.
To exclude the possibility this could be a pure RPi 4 problem, I installed the same Ubuntu version (so starting with a fresh OS) on the RPi 3. Unfortunately the same result there: no controllers detected.
Not sure if I'm missing a dependency or some other detail. I followed the commands listed on [Getting the code](https://approxeng.github.io/approxeng.input/index.html).
Versions of the dependencies are the same on the aarch64 and x86_64 Ubuntu versions:
**python3-dev:** 3.8.2-0ubuntu2
**python3:** 3.8.5
**gcc:** (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Regards,
Niko

**Comment by ghost** [comment]
Found the solution. In my configuration I need to run the `approxeng_input` commands with sudo permissions.

**Comment by tomoinn** [comment]
I think a better approach might be to create or use an appropriate group. You shouldn't ever need to use sudo to access a joystick! See this answer for more detail - https://stackoverflow.com/questions/13220566/linux-raw-input-without-root-permission (both for checking existing groups, and for creating udev rules to assign devices to a new input group)

**Comment by ghost** [comment]
Followed the solution in your link and it works now without sudo. Way better solution that way!
Thank you!
