### ISSUE TITLE
vibration support

### ISSUE THREAD

**Issue by umeiko** [ApproxEng/approxeng.input#53]
Can this library support the control of the handle vibration motor? How to achieve it ？

**Comment by tomoinn** [comment]
The library doesn't provide support for this at the moment, although you can create a custom controller class and handle this in the same way I've handled e.g. the PS4 controller light bar by adding methods specifically for it. There's some help in the library for finding the right nodes in /sys if you want to do this, it's not something I've tried though.

What controller are you trying to use?

**Comment by tomoinn** [comment]
So as of 2.6.3 (released just now) it can, just call `joystick.rumble(500)` for example to create a half second of rumbling. Obviously this only works if you have a controller which actually has the hardware, my PS4 controller works with it for example.
