### ISSUE TITLE
File not found: /sys/class/leds/default-on/device/uevent

### ISSUE THREAD

**Issue by Richard-Gemmell** [ApproxEng/approxeng.input#55]
Hi,

First of all, thanks very much for providing this library. It made it much, much easier for me to get going in PiWars.

I updated the packages on my Pi recently and I now get this error when my controller connects:

```
  File "/usr/local/lib/python3.7/dist-packages/approxeng/input/selectbinder.py", line 131, in bind_controllers
    sys.scan_cache(force_update=True)
  File "/usr/local/lib/python3.7/dist-packages/approxeng/input/sys.py", line 23, in scan_cache
    __CACHED_SCAN__ = scan_system()
  File "/usr/local/lib/python3.7/dist-packages/approxeng/input/sys.py", line 126, in scan_system
    device_id = find_device_hardware_id(sub + '/device/uevent')
  File "/usr/local/lib/python3.7/dist-packages/approxeng/input/sys.py", line 107, in find_device_hardware_id
    for line in open(uevent_file_path, 'r').read().split('\n'):
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/leds/default-on/device/uevent'
```

The problem is that `/sys/class/leds/default-on/` doesn't contain a `device` directory.

Catching the file not found exception like this fixes the issue:
    https://github.com/ApproxEng/approxeng.input/commit/f0633b378359febea8de29ed9e83ffd17479246d

Is this a problem with my Pi?

cheers,
Richard (Team Gremlin)

**Comment by tomoinn** [comment]
Hi Richard,

What controller are you using? Sounds like a library bug rather than a Pi issue, I'm curious where that 'default-on' is coming from though. Will have a dig and get back to you.

**Comment by tomoinn** [comment]
Ah, this is fixed in https://github.com/ApproxEng/approxeng.input/pull/39 I just haven't done a release since that point. Thanks for reminding me!

**Comment by tomoinn** [comment]
I've pushed 2.6.3 which includes this change, should be fine now hopefully if you do a `pip install --upgrade`

**Comment by Richard-Gemmell** [comment]
That works. Thanks very much.

I upgraded PyYAML which took it to 5.4.1. It complained that approxeng.input requires 5.4 but it seems Ok to far.
