### ISSUE TITLE
Add simple methods to Contoller to make it easy to use with GPIOzero

### ISSUE THREAD

**Issue by tomoinn** [ApproxEng/approxeng.input#6]
The 'stream' (not really) API used by GPIO-zero is questionable, but it's easy to support as the 'streams' are just generators which return appropriate sequences of values. This is also pretty easy to do without library support really, but a helper function and some docs will make it even easier.

**Comment by keithellis74** [comment]
Tom, this worked for me
```pyhton
from gpiozero import Robot
from approxeng.input.selectbinder import ControllerResource

robot = Robot(left=(4, 14), right=(17, 18))

with ControllerResource() as joystick:
    while True
        ly = joystick.axes.get_value('ly')
        ry = joystick.axes.get_value('ry')
        robot.value = (ly, ry)
```
Does it need to be different to this?

**Comment by tomoinn** [comment]
Added stream methods and documented them in a relatively recent version
