### ISSUE TITLE
Installation/Build Fails Due to PyYaml 5.4 "licence_file is deprecated"

### ISSUE THREAD

**Issue by kneave** [ApproxEng/approxeng.input#62]
PyYaml 5.4 installation is broken due to a known [issue](https://github.com/yaml/pyyaml/issues/724), upgrading to PyYaml 6.0.1 fixes this, I'm in the process of raising a PR for this but thought I'd put an issue here in case people come looking for a fix.

**Comment by usedbytes** [comment]
We hit this with someone at Makespace today - new Raspberry Pi OS can't install approxeng.input.
Updating pyyaml to 6.0.1 and evdev to 1.6.1 worked

**Comment by kneave** [comment]
Merged and deployed, closing the issue.
