### ISSUE TITLE
Fresh install on Raspberry Pi not working

### ISSUE THREAD

**Issue by chunk100** [ApproxEng/approxeng.input#64]
Im trying a fresh install on a Raspberry pi Zero 2 with the latest PiOS.  However, it wont install,  with "error: externally-managed-environment".  Using sudo apt install approxeng.input cant find it.

Any help would be appreciated

pi@raspberrypi:~ $ pip3 install pigpio
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

pi@raspberrypi:~ $ sudo apt install approxeng.input
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package approxeng.input
E: Couldn't find any package by glob 'approxeng.input'

**Comment by tomoinn** [comment]
This library is intended to be installed using pip, ideally into a virtual environment. There is no system package to install with apt so that's behaving as expected. Create a new virtual environment for your project and install the library using 'python -m pip install approxeng.input' and it'll work.
