### ISSUE TITLE
Connection of Bluetooth devices

### ISSUE THREAD

**Issue by keithellis74** [ApproxEng/approxeng.input#8]
To get bluetooth devices connected I have been doing it manually via `bluetoothctl`, it would be nice if this could be rolled into a function to search for remotes, pair, trust and disconnect etc.

**Comment by tomoinn** [comment]
I don't think this really belongs in the library, I mean, bluetoothctl pretty much is that interface really. It'd just be re-inventing that, and for the purposes I'm envisaging for the library it's not likely to really add anything.
